Make gpgcheck and repo_gpgcheck configurable for yum
geerlingguy/ansible-role-kubernetes pull request #99
Opened 2021-04-05 15:53 UTC by rhino5oh

At the time of this PR, this role is currently failing on CentOS 7 distros with a `repomd.xml signature could not be verified for kubernetes` error. 

This appears to be an upstream issue, and an issue that unfortunately crops up somewhat often. However, it can be worked around with a change to make some yum_repository options configurable. See [here](https://github.com/kubernetes/kubernetes/issues/60134), also [here](https://github.com/kubernetes/release/issues/1982), and most importantly see the official suggestion from Google [here](https://cloud.google.com/compute/docs/troubleshooting/known-issues#keyexpired)

This PR makes gpgcheck and repo_gpgcheck configurable so that they can be changed. Setting repo_gpgcheck to 'false' prevents the "signature could not be verified for kubernetes" issue.

2021-04-07 14:40 UTC, geerlingguy commented
Setting any kind of GPG check to false by default feels wrong to me...

2021-04-07 15:10 UTC, rhino5oh commented
Couldn't agree more! Unfortunately that's Google's official suggestion for this known issue.

2021-07-07 02:51 UTC, geerlingguy requested changes

2021-07-07 02:51 UTC, geerlingguy commented on README.md
> +    kubernetes_repo_gpg_check: false
I'd be willing to merge this if the defaults are kept as `true`. Someone can then override if need be, but the default should remain secure.

2021-08-23 12:29 UTC, geerlingguy commented
Closed in favor of #110

2021-08-23 12:29 UTC, closed without merging